export default {
	EXAM_CREATE: 'EXAM_CREATE',
	EXAM_SAVE: 'EXAM_SAVE',
	EXAM_REMOVE: 'EXAM_REMOVE',
	EXAM_EDIT: 'EXAM_EDIT',
	EXAM_LOAD: 'EXAM_LOAD',
	EXAM_LOAD_ONE: 'EXAM_LOAD_ONE',
	EXAM_LOAD_QUESTIONS: 'EXAM_LOAD_QUESTIONS',
};