export default {
	QUESTION_CREATE: 'QUESTION_CREATE',
	QUESTION_SAVE: 'QUESTION_SAVE',
	QUESTION_REMOVE: 'QUESTION_REMOVE',
	QUESTION_EDIT: 'QUESTION_EDIT',
	QUESTION_LOAD: 'QUESTION_LOAD',
	QUESTION_LOAD_CHOICES: 'QUESTION_LOAD_CHOICES',
};